name: pr verify

on: [push, pull_request]

jobs:
  pr_verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          presist-credentials: false
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: npm ci
      - name: validate
        run: npm run verify
      - name: e2e
        run: npm run e2e